# Hadoop HA Cluster Inventory

[all:vars]
# Here we define the logic cluster names
hdfs_cluster_name=mycluster
yarn_cluster_name=yarn-cluster

[zookeepers]
spark01 ansible_host=192.168.9.41 myid=1
spark02 ansible_host=192.168.9.42 myid=2
spark03 ansible_host=192.168.9.43 myid=3

[namenodes]
spark01 ansible_host=192.168.9.41 nn_id=nn1
spark02 ansible_host=192.168.9.42 nn_id=nn2

[resourcemanagers]
spark01 ansible_host=192.168.9.41 rm_id=rm1
spark03 ansible_host=192.168.9.43 rm_id=rm2

[journalnodes]
spark04 ansible_host=192.168.9.44
spark05 ansible_host=192.168.9.45
spark06 ansible_host=192.168.9.46

[workers]
spark04 ansible_host=192.168.9.44
spark05 ansible_host=192.168.9.45
spark06 ansible_host=192.168.9.46

[spark_clients]
spark04 ansible_host=192.168.9.44
spark05 ansible_host=192.168.9.45
spark06 ansible_host=192.168.9.46
